#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS
FILE="/etc/passwd"

while IFS=: read -r username password userid groupid useridinfo homedir cmdshell
do
  echo -n "The user $username is part of the $groupid gang, lives in $homedir "
  echo -n "and rides $cmdshell. $userid's place is protected by the passcode "
  echo "$password, more info about the user here: $useridinfo"
done < $FILE
