#!/usr/bin/env bash
# Prints "Holberton School" 10 times, for the 9th iteration prints
# "Holberton School" and then "Hi" followed by a new line
i=1
while ((i <= 10))
do
if ((i == 10))
then
   echo "Hi"
fi
echo "Holberton School"
i=$((i + 1))
done
