#!/usr/bin/env bash
# Loop from 1 to 10, displays "bad luck" for the 4th iteration,
# displays "good luck" for the 8th iteration and "Holberton School"
# for the other ones
i=1
while ((i <= 10))
do
if ((i == 4))
then
    echo "bad luck"
elif ((i == 8))
then
    echo "good luck"
else
    echo "Holberton School"
fi
i=$((i + 1))
done
